/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpit251project;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class appointments extends javax.swing.JFrame {
     String choice="";
     String name="";
     String number="";
     String service="";
     Date appDate;
     Date today = new Date();
     ArrayList<appointments> list = new ArrayList<appointments>();
     double price ;

    public appointments() {
        
        initComponents();
        calender.setMinSelectableDate(today);
        visibleForApp(false);
       
        
    }
        public appointments(String name, String number,String service,Date appDate){
        this.name = name;
        this.number =number;
        this.service=service;
        this.appDate=appDate;
     } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bookAnApp = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        enterNameLabel = new javax.swing.JLabel();
        writtenName = new javax.swing.JTextField();
        writtenNum = new javax.swing.JTextField();
        enterNumberLabel = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        selectedService = new javax.swing.JComboBox<>();
        calender = new com.toedter.calendar.JDateChooser();
        outPrice = new java.awt.Label();
        doneButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        bookAnApp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookAnApp.setText("book an appointment");
        bookAnApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAnAppActionPerformed(evt);
            }
        });
        jPanel1.add(bookAnApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("canceal an appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        enterNameLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        enterNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterNameLabel.setText("Enter your name ");
        jPanel1.add(enterNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        writtenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writtenNameActionPerformed(evt);
            }
        });
        jPanel1.add(writtenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 210, 40));
        jPanel1.add(writtenNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 210, 40));

        enterNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        enterNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterNumberLabel.setText("Enter your number");
        jPanel1.add(enterNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        serviceLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        serviceLabel.setForeground(new java.awt.Color(255, 255, 255));
        serviceLabel.setText("choose a service");
        jPanel1.add(serviceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("choose a date");
        jPanel1.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        selectedService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose", "cutthing hair", "painting nails ", "makeup", "blow dry hair ", "remove body hair" }));
        selectedService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedServiceActionPerformed(evt);
            }
        });
        jPanel1.add(selectedService, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 160, 40));

        calender.setDateFormatString("d/M/yyyy");
        jPanel1.add(calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 160, 40));
        jPanel1.add(outPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 100, 40));

        doneButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        homeButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cpit251project/Screenshot_16.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void visibleForApp(boolean visibility){
        writtenName.setVisible(visibility);
        writtenNum.setVisible(visibility);
        selectedService.setVisible(visibility);
        outPrice.setVisible(visibility);
        calender.setVisible(visibility);
        enterNumberLabel.setVisible(visibility);
        serviceLabel.setVisible(visibility);
        enterNameLabel.setVisible(visibility);
        dateLabel.setVisible(visibility);
        doneButton.setVisible(visibility);
    }
    
    
    
    private void bookAnAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAnAppActionPerformed
        // TODO add your handling code here:
        visibleForApp(true);
        choice = "booking";
    }//GEN-LAST:event_bookAnAppActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        choice = "cancealing";
         visibleForApp(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void writtenNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writtenNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writtenNameActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
         if(choice.equalsIgnoreCase("booking")){
            if(isBookingValid()){
            appointments app = new appointments(name,number,service,appDate);
            list.add(app);   
            } 
            
         }else 
              System.out.println("");
        
    }//GEN-LAST:event_doneButtonActionPerformed
    public boolean isBookingValid(){
        String mass="";
        String at1= writtenName.getText();
        String at2 = writtenNum.getText();
        String at3=selectedService.getSelectedItem().toString();
        Date at4 = calender.getDate();
        if(!at1.isEmpty())
        name = at1;
        else
            mass+="Write your name pleas \n";
        if(!at2.isEmpty()&at2.length()==10&!at2.matches("[0-9]+"))
        number=at2;
        else 
            mass+="Write your number pleas or check that it's 10 digit\n"; 
        if(!at3.equalsIgnoreCase("choose"))
        service= at3;
        else
           mass+="choose a service \n";  
        if(at4!=null)
        appDate= at4;
        else 
           mass+="choose date pleas \n"; 

        if(!mass.isEmpty()){
            JOptionPane.showMessageDialog(this,mass);  
            return false;
        }
       else
        {
        JOptionPane.showMessageDialog(this,"your appointment added successfully"); 
        return true;
        }
    }
    
    
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
         main_page m= new main_page();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void selectedServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedServiceActionPerformed
        // TODO add your handling code here:
          service =selectedService.getSelectedItem().toString();
          if(!service.equalsIgnoreCase("choose")){
            if(service.equalsIgnoreCase("cutthing hair"))
              outPrice.setText("60 sr");
            else if(service.equalsIgnoreCase("painting nails"))
              outPrice.setText("45 sr");
            else if(service.equalsIgnoreCase("makeup"))
              outPrice.setText("50 sr");
            else if(service.equalsIgnoreCase("blow dry hair "))
              outPrice.setText("40 sr");
            else
              outPrice.setText("100 sr");
           
            
        }else 
           outPrice.setText("");
        
        
    }//GEN-LAST:event_selectedServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appointments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookAnApp;
    private com.toedter.calendar.JDateChooser calender;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JLabel enterNumberLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label outPrice;
    private javax.swing.JComboBox<String> selectedService;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JTextField writtenName;
    private javax.swing.JTextField writtenNum;
    // End of variables declaration//GEN-END:variables
}
